apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
  labels:
    tier: petclinic-dev
  name: petclinic-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: petclinic-dev
  template:
    metadata:
      labels:
        tier: petclinic-dev
    spec:
      containers:
        - image: harbor.pks.pivot.host/tybritten/spring-petclinic
          imagePullPolicy: Always
          name: petclinic-dev
      imagePullSecrets:
        - name: harbor

